name: reusable-ci

on:
  workflow_call:
    inputs:
      workdir:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    concurrency:
      group: ci-${{ github.ref }}-${{ inputs.workdir }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ${{ inputs.workdir }}/package-lock.json
      - run: npm ci
      - run: npm test --if-present -- --ci
      - run: npm run build --if-present
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.workdir }}-build
          path: ${{ inputs.workdir }}/dist
