name: CI
on:
  pull_request:
    branches: [development, main]
  push:
    branches: [development]

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/order_service

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # cache: npm
          # cache-dependency-path: backend/order_service/package-lock.json

      - name: Ensure npm cache dir exists
        run: |
          mkdir -p "$(npm config get cache)"

      - name: Verify lockfile
        run: |
          test -f package-lock.json || { 
            echo "ERROR: package-lock.json missing in backend/order_service .";
            exit 1;
          }

      - name: Install deps
        run: npm ci

      - name: Test
        run: npm test --if-present -- --ci

      - name: Build
        run: npm run build --if-present

      - name: Upload artifact
        if: ${{ hashFiles('dist/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: order_service-build
          path: dist
