name: CI

on:
  pull_request:
    branches: [ development, main ]
  push:
    branches: [ development ]

jobs:
  matrix-ci:
    strategy:
      matrix:
        app: [ 'frontend', 'backend' ]
    uses: ./.github/workflows/ci-reusable.yml
    with:
      workdir: ${{ matrix.app }}
