name: CI
on:
  pull_request:
    branches: [development, main]
  push:
    branches: [development]

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/order_service

    steps:
      - uses: actions/checkout@v4

      # DEBUG: show files so we confirm paths exist
      - name: Debug tree
        run: |
          pwd
          ls -la
          ls -la backend || true
          ls -la backend/order_service || true
          test -f package.json && echo "found package.json"
          test -f package-lock.json && echo "found package-lock.json" || true

      - name: Setup Node (npm cache via lockfile)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # cache: npm
          # # Because working-directory is set, this path is relative to it:
          # cache-dependency-path: backend/order_service/package-lock.json


      - name: Install deps
        run: npm ci

      - name: Test
        run: npm test --if-present -- --ci

      - name: Build
        run: npm run build --if-present

      - name: Upload artifact
        if: ${{ hashFiles('dist/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: order_service-build
          path: dist
