# .github/workflows/deploy-prod.yml
name: Deploy to Prod

on:
  workflow_run:
    workflows: [ "CI" ]     # must match CI workflow name exactly
    types: [ "completed" ]
    branches: [ "main" ]

permissions:
  actions: read
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://your-production-url.com

    steps:
      - name: Download frontend artifact from CI run
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend-dist
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download backend artifact from CI run
        uses: actions/download-artifact@v4
        with:
          name: backend-build
          path: backend-dist
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "Deploying to Production…"
